project:
  type: website
  output-dir: docs
  resources:
    - Schedule/*

website:
  title: "FoolsFest 2025"
  favicon: jesters_cap_icon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Event_Info.qmd
      - RSVP.qmd
      - Venue_Photos.qmd
      - Map.qmd
      - FAQ.qmd
      - Posts.qmd
      - href: /Schedule
        text: Schedule

format:
  html:
    theme: solar
    css: styles.css
    toc: true
