project:
  type: website
  output-dir: docs
  resources:
    - Schedule/*
    - img/**
website:
  title: "FoolsFest 2025"
  favicon: jesters_cap_icon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Event_Info.qmd
        text: Event Info
      - href: RSVP.qmd
        text: RSVP
      - href: Venue_Photos.qmd
        text: Venue Photos
      - href: Map.qmd
        text: Map
      - href: FAQ.qmd
        text: FAQ
      - href: Sponsors.qmd
        text: Sponsors
      #- href: /Schedule
        #text: Schedule


format:
  html:
    theme: solar
    css: styles.css
    toc: true
