project:
  type: website
  output-dir: docs

website:
  title: "FoolsFest 2024"
  favicon: jesters_cap_icon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - FAQ.qmd
      - Venue.qmd
      - Map.qmd
       
      

format:
  html:
    theme: solar
    css: styles.css
    toc: true
    



